### PR TITLE
Preload all instrument response in API, faster pre-processing

### PR DESCRIPTION
**Pull request by ThomasLecocq**
discussed in #85 , #87 with Rob. 

This PR should pass transparently. The instrument response of all channels is pre-loaded at pre-processing step (could actually be in compute_cc)

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
@RobertGreen could you give this PR a test in the coming days ?

**Comment by ThomasLecocq** [comment]
these are timing results with and without instrument response computation

```sh
C:\tmp\msnoise1.5>msnoise compute_cc
2017-04-10 15:40:37 [INFO] *** Starting: Compute CC ***
2017-04-10 15:40:37 [INFO] Will compute ZZ
2017-04-10 15:40:38 [INFO] New CC Job: 2010-09-01 (3 pairs with 3 stations)
2017-04-10 15:40:46 [INFO] Processing pair: YA.UV05 vs YA.UV06
2017-04-10 15:40:47 [INFO] Finished processing this pair. It took 1.57 seconds
2017-04-10 15:40:47 [INFO] Processing pair: YA.UV05 vs YA.UV10
2017-04-10 15:40:49 [INFO] Finished processing this pair. It took 1.61 seconds
2017-04-10 15:40:49 [INFO] Processing pair: YA.UV06 vs YA.UV10
2017-04-10 15:40:51 [INFO] Finished processing this pair. It took 1.56 seconds
2017-04-10 15:40:51 [INFO] Job Finished. It took 12.93 seconds
2017-04-10 15:40:51 [INFO] New CC Job: 2010-09-02 (3 pairs with 3 stations)
2017-04-10 15:40:58 [INFO] Processing pair: YA.UV05 vs YA.UV06
2017-04-10 15:41:00 [INFO] Finished processing this pair. It took 1.54 seconds
2017-04-10 15:41:00 [INFO] Processing pair: YA.UV05 vs YA.UV10
2017-04-10 15:41:01 [INFO] Finished processing this pair. It took 1.57 seconds
2017-04-10 15:41:01 [INFO] Processing pair: YA.UV06 vs YA.UV10
2017-04-10 15:41:03 [INFO] Finished processing this pair. It took 1.56 seconds
2017-04-10 15:41:03 [INFO] Job Finished. It took 12.33 seconds
2017-04-10 15:41:03 [INFO] *** Finished: Compute CC ***

C:\tmp\msnoise1.5>msnoise config --set remove_response=N
Successfully updated parameter remove_response = N

C:\tmp\msnoise1.5>msnoise reset CC --all

C:\tmp\msnoise1.5>msnoise compute_cc
2017-04-10 15:41:34 [INFO] *** Starting: Compute CC ***
2017-04-10 15:41:34 [INFO] Will compute ZZ
2017-04-10 15:41:34 [INFO] New CC Job: 2010-09-01 (3 pairs with 3 stations)
2017-04-10 15:41:40 [INFO] Processing pair: YA.UV05 vs YA.UV06
2017-04-10 15:41:41 [INFO] Finished processing this pair. It took 1.64 seconds
2017-04-10 15:41:41 [INFO] Processing pair: YA.UV05 vs YA.UV10
2017-04-10 15:41:43 [INFO] Finished processing this pair. It took 1.60 seconds
2017-04-10 15:41:43 [INFO] Processing pair: YA.UV06 vs YA.UV10
2017-04-10 15:41:44 [INFO] Finished processing this pair. It took 1.57 seconds
2017-04-10 15:41:44 [INFO] Job Finished. It took 10.13 seconds
2017-04-10 15:41:45 [INFO] New CC Job: 2010-09-02 (3 pairs with 3 stations)
2017-04-10 15:41:50 [INFO] Processing pair: YA.UV05 vs YA.UV06
2017-04-10 15:41:51 [INFO] Finished processing this pair. It took 1.60 seconds
2017-04-10 15:41:51 [INFO] Processing pair: YA.UV05 vs YA.UV10
2017-04-10 15:41:53 [INFO] Finished processing this pair. It took 1.54 seconds
2017-04-10 15:41:53 [INFO] Processing pair: YA.UV06 vs YA.UV10
2017-04-10 15:41:55 [INFO] Finished processing this pair. It took 1.55 seconds
2017-04-10 15:41:55 [INFO] Job Finished. It took 10.04 seconds
2017-04-10 15:41:55 [INFO] *** Finished: Compute CC ***
```

**Comment by RobertGGreen** [comment]
Excellent, yes I shall give it a go in the next day or two.

**Comment by ThomasLecocq** [comment]
I merged it in Master so you can pip install master directly to test

**Comment by RobertGGreen** [comment]
Hi Tom,

I’ve tried it on my linux machine and it runs successfully. 

Here is the output so it at least runs, though I haven’t checked if the response removal was correct. 
The instrument response removal is remarkably quick. Putting it in the api was a great idea. 
I shall do some more testing tomorrow. 


rgcg3@uranus:/raid1/rgcg3/msnoise/bardabungatomo$ msnoise compute_cc
2017-04-12 16:54:11 [INFO] *** Starting: Compute CC ***
2017-04-12 16:54:11 [INFO] Will compute ZZ RR TT
2017-04-12 16:54:11 [DEBUG] Pre-loading all instrument response
2017-04-12 16:54:11 [DEBUG] Removing instrument response
2017-04-12 16:54:25 [INFO] New CC Job: 2013-09-01 (378 pairs with 28 stations)
2017-04-12 16:54:26 [DEBUG] Z7.BHAF.E Reading 1 Files
2017-04-12 16:54:26 [DEBUG] Checking sample alignment
2017-04-12 16:54:26 [DEBUG] Checking Gaps
2017-04-12 16:54:29 [DEBUG] Z7.BHAF.E Highpass at 0.02 Hz
2017-04-12 16:54:29 [DEBUG] Z7.BHAF.E Lowpass at 5.00 Hz
2017-04-12 16:54:29 [DEBUG] Z7.BHAF.E Decimate by a factor of 10
2017-04-12 16:54:29 [DEBUG] Z7.BHAF..HHE Removing instrument response
2017-04-12 16:54:30 [DEBUG] Z7.BHAF.N Reading 1 Files
2017-04-12 16:54:30 [DEBUG] Checking sample alignment
2017-04-12 16:54:30 [DEBUG] Checking Gaps
2017-04-12 16:54:31 [DEBUG] Z7.BHAF.N Highpass at 0.02 Hz
2017-04-12 16:54:32 [DEBUG] Z7.BHAF.N Lowpass at 5.00 Hz
2017-04-12 16:54:32 [DEBUG] Z7.BHAF.N Decimate by a factor of 10
2017-04-12 16:54:32 [DEBUG] Z7.BHAF..HHN Removing instrument response
2017-04-12 16:54:33 [DEBUG] Z7.BHAF.Z Reading 1 Files
2017-04-12 16:54:33 [DEBUG] Checking sample alignment
2017-04-12 16:54:33 [DEBUG] Checking Gaps
2017-04-12 16:54:34 [DEBUG] Z7.BHAF.Z Highpass at 0.02 Hz
2017-04-12 16:54:34 [DEBUG] Z7.BHAF.Z Lowpass at 5.00 Hz
2017-04-12 16:54:35 [DEBUG] Z7.BHAF.Z Decimate by a factor of 10
2017-04-12 16:54:35 [DEBUG] Z7.BHAF..HHZ Removing instrument response
2017-04-12 16:54:35 [DEBUG] Z7.BOTN.E Reading 1 Files



Incidentally I tried it on my mac (which used to work a while back) and was having problems with scipy but the most recent version solved that. 
I’ve got to go right now to i’ll investigate it later, but here is the error in case it makes immediate sense before. Don’t worry if not because it is with a different database and dataset on my laptop compared to the linux machine. There could well be a load of other errors in there.

Roberts-MacBook-Pro-6:askja_mini robertgreen$ msnoise compute_cc
2017-04-12 18:06:35 [INFO] *** Starting: Compute CC ***
2017-04-12 18:06:35 [INFO] Will compute 
2017-04-12 18:06:35 [DEBUG] Pre-loading all instrument response
2017-04-12 18:06:35 [DEBUG] Removing instrument response
2017-04-12 18:06:35 [INFO] New CC Job: 2011-10-11 (6 pairs with 4 stations)
Process Process-1:
Traceback (most recent call last):
  File "/Users/robertgreen/software/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/robertgreen/software/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/robertgreen/software/anaconda2/lib/python2.7/site-packages/msnoise-1.5a0-py2.7.egg/msnoise/s03compute_cc.py", line 241, in main
    if comp[0] in ["R", "T"] or comp[1] in ["R", "T"]:
IndexError: string index out of range


---------------
Robert Green
Research Associate - Seismology
Dept of Earth Sciences - Bullard Labs, University of Cambridge

**Comment by RobertGGreen** [comment]
Actually the MAC error is more likely to be header errors in the test dataset I have on my Mac, so ignore that comment.

**Comment by RobertGGreen** [comment]
Hi Tom,

I did some more testing. The instrument response is very successful, but I found a bug on my mac from some of the newer bits of your update_data_availability and update_jobs in the api. See further down for info on that.

Timings here for a quick test run, deliberately with a file lacking instrument response to induce a failure. The times are identical for both with and without response removal. I threw in a print response before the simulate and the responses seemed fine though so it is just running well. 

With response removal:
Roberts-MacBook-Pro-6:msnoise_test robertgreen$ msnoise compute_cc
2017-04-13 17:22:03 [INFO] *** Starting: Compute CC ***
2017-04-13 17:22:03 [INFO] Will compute ZZ
2017-04-13 17:22:03 [DEBUG] Pre-loading all instrument response
2017-04-13 17:22:03 [DEBUG] Removing instrument response
2017-04-13 17:22:16 [INFO] New CC Job: 2011-10-10 (28 pairs with 8 stations)
2017-04-13 17:22:16 [DEBUG] Z7.ASK.Z Reading 1 Files
2017-04-13 17:22:16 [DEBUG] Checking sample alignment
2017-04-13 17:22:16 [DEBUG] Checking Gaps
2017-04-13 17:22:17 [DEBUG] Z7.ASK.Z Highpass at 0.01 Hz
2017-04-13 17:22:17 [DEBUG] Z7.ASK.Z Lowpass at 8.00 Hz
2017-04-13 17:22:17 [DEBUG] Z7.ASK.Z Downsample to 20.0 Hz
2017-04-13 17:22:18 [DEBUG] Z7.ASK..HHZ Removing instrument response
2017-04-13 17:22:18 [DEBUG] Z7.BRUN.Z Reading 1 Files
2017-04-13 17:22:18 [DEBUG] Checking sample alignment
2017-04-13 17:22:18 [DEBUG] Checking Gaps
2017-04-13 17:22:19 [DEBUG] Z7.BRUN.Z Highpass at 0.01 Hz
2017-04-13 17:22:19 [DEBUG] Z7.BRUN.Z Lowpass at 8.00 Hz
2017-04-13 17:22:20 [DEBUG] Z7.BRUN.Z Downsample to 20.0 Hz
2017-04-13 17:22:20 [DEBUG] Z7.BRUN..HHZ Removing instrument response
2017-04-13 17:22:21 [DEBUG] Z7.FLAT.Z Reading 1 Files
2017-04-13 17:22:21 [DEBUG] Checking sample alignment
2017-04-13 17:22:21 [DEBUG] Checking Gaps
2017-04-13 17:22:22 [DEBUG] Z7.FLAT.Z Highpass at 0.01 Hz
2017-04-13 17:22:22 [DEBUG] Z7.FLAT.Z Lowpass at 8.00 Hz
2017-04-13 17:22:22 [DEBUG] Z7.FLAT.Z Downsample to 20.0 Hz
2017-04-13 17:22:23 [DEBUG] Z7.FLAT..HHZ Removing instrument response
2017-04-13 17:22:23 [DEBUG] Z7.KOLL.Z Reading 1 Files
2017-04-13 17:22:23 [DEBUG] Checking sample alignment
2017-04-13 17:22:23 [DEBUG] Checking Gaps
2017-04-13 17:22:24 [DEBUG] Z7.KOLL.Z Highpass at 0.01 Hz
2017-04-13 17:22:24 [DEBUG] Z7.KOLL.Z Lowpass at 8.00 Hz
2017-04-13 17:22:25 [DEBUG] Z7.KOLL.Z Downsample to 20.0 Hz
2017-04-13 17:22:25 [DEBUG] Z7.KOLL..HHZ Removing instrument response
2017-04-13 17:22:26 [DEBUG] Z7.KRE.Z Reading 1 Files
2017-04-13 17:22:26 [DEBUG] Checking sample alignment
2017-04-13 17:22:26 [DEBUG] Checking Gaps
2017-04-13 17:22:27 [DEBUG] Z7.KRE.Z Highpass at 0.01 Hz
2017-04-13 17:22:27 [DEBUG] Z7.KRE.Z Lowpass at 8.00 Hz
2017-04-13 17:22:27 [DEBUG] Z7.KRE.Z Downsample to 20.0 Hz
2017-04-13 17:22:27 [DEBUG] Z7.KRE..HHZ Removing instrument response
2017-04-13 17:22:27 [INFO] No instrument response information for Z7.KRE..HHZ, exiting


Then without instrument response removal:
Roberts-MacBook-Pro-6:msnoise_test robertgreen$ msnoise compute_cc
2017-04-13 17:24:45 [INFO] *** Starting: Compute CC ***
2017-04-13 17:24:45 [INFO] Will compute ZZ
2017-04-13 17:24:45 [INFO] New CC Job: 2011-10-10 (28 pairs with 8 stations)
2017-04-13 17:24:45 [DEBUG] Z7.ASK.Z Reading 1 Files
2017-04-13 17:24:46 [DEBUG] Checking sample alignment
2017-04-13 17:24:46 [DEBUG] Checking Gaps
2017-04-13 17:24:46 [DEBUG] Z7.ASK.Z Highpass at 0.01 Hz
2017-04-13 17:24:47 [DEBUG] Z7.ASK.Z Lowpass at 8.00 Hz
2017-04-13 17:24:47 [DEBUG] Z7.ASK.Z Downsample to 20.0 Hz
2017-04-13 17:24:47 [DEBUG] Z7.BRUN.Z Reading 1 Files
2017-04-13 17:24:47 [DEBUG] Checking sample alignment
2017-04-13 17:24:47 [DEBUG] Checking Gaps
2017-04-13 17:24:48 [DEBUG] Z7.BRUN.Z Highpass at 0.01 Hz
2017-04-13 17:24:48 [DEBUG] Z7.BRUN.Z Lowpass at 8.00 Hz
2017-04-13 17:24:49 [DEBUG] Z7.BRUN.Z Downsample to 20.0 Hz
2017-04-13 17:24:49 [DEBUG] Z7.FLAT.Z Reading 1 Files
2017-04-13 17:24:49 [DEBUG] Checking sample alignment
2017-04-13 17:24:49 [DEBUG] Checking Gaps
2017-04-13 17:24:50 [DEBUG] Z7.FLAT.Z Highpass at 0.01 Hz
2017-04-13 17:24:50 [DEBUG] Z7.FLAT.Z Lowpass at 8.00 Hz
2017-04-13 17:24:50 [DEBUG] Z7.FLAT.Z Downsample to 20.0 Hz
2017-04-13 17:24:50 [DEBUG] Z7.KOLL.Z Reading 1 Files
2017-04-13 17:24:51 [DEBUG] Checking sample alignment
2017-04-13 17:24:51 [DEBUG] Checking Gaps
2017-04-13 17:24:51 [DEBUG] Z7.KOLL.Z Highpass at 0.01 Hz
2017-04-13 17:24:51 [DEBUG] Z7.KOLL.Z Lowpass at 8.00 Hz
2017-04-13 17:24:52 [DEBUG] Z7.KOLL.Z Downsample to 20.0 Hz
2017-04-13 17:24:52 [DEBUG] Z7.KRE.Z Reading 1 Files
2017-04-13 17:24:52 [DEBUG] Checking sample alignment
2017-04-13 17:24:52 [DEBUG] Checking Gaps
2017-04-13 17:24:53 [DEBUG] Z7.KRE.Z Highpass at 0.01 Hz
2017-04-13 17:24:53 [DEBUG] Z7.KRE.Z Lowpass at 8.00 Hz
2017-04-13 17:24:53 [DEBUG] Z7.KRE.Z Downsample to 20.0 Hz


This afternoon I set up a new msnoise project from scratch and came across problems with the functions to update the database.

scan_archive was failing with the update_data_availability function. The problem (as you can see in the error message below) is in the da_index in the with_hint command.
I commented out line 489 in api.py (#with_hint(DataAvailability, 'USE INDEX (da_index)'). \) and this enabled me to skip the hint and update
the database in order to do the test of response removal.


Roberts-MacBook-Pro-6:msnoise_test robertgreen$ msnoise scan_archive --init
2017-04-13 16:27:51 [INFO] *** Starting: Scan Archive ***
2017-04-13 16:27:51 [INFO] Initializing (should be run only once)
2017-04-13 16:27:51 [INFO] Will work on 1 thread(s)
2017-04-13 16:27:51 [INFO] Will search for files between 2011-10-07 and 2011-10-27
2017-04-13 16:27:51 [DEBUG] Will search for channels: ['*']
2017-04-13 16:27:51 [DEBUG] Data Folder: /Users/robertgreen/msnoise_testset/archive
2017-04-13 16:27:51 [DEBUG] Folders to glob: /Users/robertgreen/msnoise_testset/archive/2011/*
2017-04-13 16:27:51 [DEBUG] Files detected in /Users/robertgreen/msnoise_testset/archive/2011/280 folder: 81
2017-04-13 16:27:51 [INFO] /Users/robertgreen/msnoise_testset/archive/2011/280: Started
2017-04-13 16:27:51 [DEBUG] ERROR: (pymysql.err.InternalError) (1176, u"Key 'da_index' doesn't exist in table 'data_availability'") [SQL: u'SELECT data_availability.ref AS data_availability_ref, data_availability.net AS data_availability_net, data_availability.sta AS data_availability_sta, data_availability.comp AS data_availability_comp, data_availability.path AS data_availability_path, data_availability.file AS data_availability_file, data_availability.starttime AS data_availability_starttime, data_availability.endtime AS data_availability_endtime, data_availability.data_duration AS data_availability_data_duration, data_availability.gaps_duration AS data_availability_gaps_duration, data_availability.samplerate AS data_availability_samplerate, data_availability.flag AS data_availability_flag \nFROM data_availability USE INDEX (da_index) \nWHERE data_availability.path = %(path_1)s AND data_availability.file = %(file_1)s AND data_availability.net = %(net_1)s AND data_availability.sta = %(sta_1)s AND data_availability.comp = %(comp_1)s \n LIMIT %(param_1)s'] [parameters: {u'net_1': u'Z7', u'param_1': 1, u'file_1': '2011280_000000_ASK_E2.m', u'path_1': '/Users/robertgreen/msnoise_testset/archive/2011/280', u'sta_1': u'ASK', u'comp_1': u'HHE'}]


The same problem with the hint exists with the update_job function, as this error ended the compute_cc job where it doesn’t fail with a missing instrument response.
InternalError: (pymysql.err.InternalError) (1176, u"Key 'job_index' doesn't exist in table 'jobs'") [SQL: u'SELECT jobs.ref AS jobs_ref, jobs.day AS jobs_day, jobs.pair AS jobs_pair, jobs.jobtype AS jobs_jobtype, jobs.flag AS jobs_flag, jobs.lastmod AS jobs_lastmod \nFROM jobs USE INDEX (job_index) \nWHERE jobs.day = %(day_1)s AND jobs.pair = %(pair_1)s AND jobs.jobtype = %(jobtype_1)s \n LIMIT %(param_1)s'] [parameters: {u'param_1': 1, u'day_1': '2011-10-10', u'jobtype_1': 'CC', u'pair_1': 'Z7.ASK:Z7.BRUN'}]

Commenting line 654 in api.py (.with_hint(Job, 'USE INDEX (job_index)’)\), also avoids the bug, confirming that the indexing with the hint (which I am not familiar with) is the problem.

Hope that helps.

Rob

**Comment by ThomasLecocq** [comment]
Wow, thanks for the input Rob! 

It seems the index is not created automatically for new projects, could you try with a fresh install

$ msnoise install
..
$ msnoise upgrade_db
...
and then your classic workflow ?

**Comment by RobertGGreen** [comment]
Hi Tom, Just to say I did very briefly try that when you asked but ran out of time that evening and am now off on holiday. 

My original test database that I showed you results from yesterday had been created from scratch. 

I tried the upgrade_db as you said and it takes ages (i don’t know if this was expected) even on a relatively small test database. 
So I created a brand new database, ran msnoise install then msnoise upgrade_db and it took only 10 seconds. 

However there were then problems as running the populate script with the same set up as before imported some unusual stuff (see below).

Roberts-MacBook-Pro-6:msnoise_test2 robertgreen$ msnoise populate
()
>> Populating the Station table
()
('Adding:', '2011', '300')
('Adding:', '2011', '297')
('Adding:', '2011', '298')
('Adding:', '2011', '299')

There must be some differences in expected fields for old and new station table configurations, as this should have been network and station being printed to screen if I remember correctly. Sorry I didn’t have time to investigate this. 

I’m away for a week on holiday so if you can wait i’ll follow it up when i’m back, but maybe you are pushing to release soon.
I’m kind of semi-unemployed at the moment. I’m living in Germany spending about 2/3 of my time learning german for the next 5 months, as my fellowship i’ve just won is paying for it.
So I actually quite enjoy the odd hour or two of playing with seismic data from time to time. 

Rob






---------------
Robert Green
Research Associate - Seismology
Dept of Earth Sciences - Bullard Labs, University of Cambridge

**Pull request merged**
