### PR TITLE
Insert info about DIST, AZIM,BAZIM in file heaters (If export format = SAC)

### PR DESCRIPTION
**Pull request by carmelosammarco**
I did again following your instruction @ThomasLecocq ... I hope that this time it is fine.

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
hehe, not yet :) see my comment on #44 :)

**Comment by ThomasLecocq** [comment]
You need to update s03 & s04 too :-)

**Comment by carmelosammarco** [comment]
done!!! i hope that this time is fine... let me know if the other modifications are ok for you.. where there wasn't session i put 'db' as first..

**Comment by ThomasLecocq** [comment]
Yeah, I know, crap naming... I think it's good...

one remaining thing would be to edit the doc string, mentioning the arguments type & definition :)

**Comment by ThomasLecocq** [comment]
@carmelosammarco :  the tests did not pass on your modifications : see https://travis-ci.org/ROBelgium/MSNoise/builds/53997144#L1894 

(for some bad reason, Travis does not catch failing tests, I have to look into that).

Could you check your code and run the tests on your machine to see if all pass ? To run the tests, you have to "python setup.py install" msnoise, so it's properly installed, then create a temporary folder somewhere, cd into it, then run "msnoise test" ... if all goes OK it shoudl finish saying "all tests OK" ;)

**Comment by ThomasLecocq** [comment]
I'm re-running the Travis build on your PR to check !

**Comment by ThomasLecocq** [comment]
Perfect:it fails :) ! So ... now, you know it needs correction: check the "details" of the travis build and you'll see what failed !

**Pull request closed without merging**
