### PR TITLE
Populate using dictionary

### PR DESCRIPTION
**Pull request by RobertGGreen**
This is a PR for the changes I made to s002populate_station_table.py, but I have not included any of the response removal changes I made for now.

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
Rob, could you add me to the "developers" list of your github msnoise repo, so I can correct a few merging issues and it'll update this PR directly ?

**Comment by ThomasLecocq** [comment]
about the instrument response I did already add some (doing the response removal after decimation, and using PAZ for dataless). I haven't yet included the paz from inventory.

**Comment by RobertGGreen** [comment]
I’ve added you as a collaborator on the repository.

Yeah I noted those bits that you had changed about changing the order, and using get_paz. 

Are you going to change the point at which you load the dataless/inventory?
At the moment in preprocessing.py you do this on lines 136 and 152, which means that the loading of the inventories or dataless object is done for every file. For large dataless/inventory files the load step can take a long time. I remember it took around 10-15 seconds to load our large dataless seed files, which is longer than the actual simulate step.

My quick fix had been to move the dataless/inventory load to the beginning of the loop so that it was done once for each job. However you previously mentioned thinking about moving the load of the inventory to the API which would of course be the best way to do it.

Rob






---------------
Robert Green
Research Associate - Seismology
Dept of Earth Sciences - Bullard Labs, University of Cambridge

**Comment by ThomasLecocq** [comment]
ok; this is driving me crazy again. I will make the changes on another branch and PR it.

**Comment by ThomasLecocq** [comment]
done in #88

**Pull request closed without merging**
