### PR TITLE
New plot type: ccf_freq

### PR DESCRIPTION
**Pull request by heavelock**
I needed a new plot type, similar to ccftime but in frequency domain. Check this out.
ccf_time_github

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
Hehe, really cool :) I actually coded that one live during the Cargèse Workshop and never finalized it !

**Comment by heavelock** [comment]
Cool! That's good that this plot can be useful for somebody else than me :)

I've updated docs and added an example image, for me it looks like almost complete. What do you think?

**Comment by ThomasLecocq** [comment]
Could you try to do only one thing per PR ? I mean, not refactoring PEP8 , adding starttime/endtime and adding a new feature at once ? It's tricky to understand as a "single PR".

to remain consistent with the ``ccftime`` I'd call the new plot ``ccffreq`` or ``ccfspec`` without underscore.

**Comment by heavelock** [comment]
Sure, I will try to be more concentrated in future PRs :) 

Yup, I will rename it.

**Comment by ThomasLecocq** [comment]
will be closed once #140 pass

**Pull request closed without merging**
