### PR TITLE
Subdaily

### PR DESCRIPTION
**Pull request by rantanplan77**
This PR adds the possibility for subdaily output. This can be useful if your corr_duration is very short, and you still want a subdaily resolution.

Additionally, it includes the filter information to the distance plot.

### CODE REVIEW

**Comment by rantanplan77** [comment]
BTW, the tests fail because of AppVeyor Py 2.7, I think there's something wrong with the configuration there...

**Comment by ThomasLecocq** [comment]
Hi Lukas,

How is this different from exporting the keep_all to H5 ?

**Comment by rantanplan77** [comment]
Say your corr_duration is 10 min, and you want to stacks of 4h. This directly produces what you want without filling your HD.

**Comment by ThomasLecocq** [comment]
not merging for now, we'll discuss it later. :-)

**Pull request closed without merging**
