### PR TITLE
Updates to stretch.py

### LINKED ISSUE #220: stretch.py expecting old file naming structure
Minor issue, stretch.py currently searches for MSEED files using old naming structure ('_' between network, station code, and location). So will always fail to find the reference stacks.

Easily fixed just making the change on line 105 of stretch.py:

```ref_name = pair.replace('.', '_' ).replace(':',  '_')```

to 

```ref_name = pair.replace(':', '_')```

### PR DESCRIPTION
**Pull request by asyates**
Made changes to stretch.py to match new file name structure + api.py changes (otherwise would never find reference files).

resolves #220

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
all checks are 🟢  so I'm OK to merge if you think it's done ?

**Comment by asyates** [comment]
Oh in fact... just realised after looking at the output, i've used the wrong function for getting the current function. Silly mistake... will fix now. My first msnoise commit will have to wait a moment longer!

**Comment by ThomasLecocq** [comment]
@asyates if your "mistake" is due to a bad API documentation, please suggest changes there too !

**Comment by asyates** [comment]
no no, definitely on me. Wouldn't have taken too many more braincells to realise cur = get_ref(...) is not the function that was required :P.

**Comment by asyates** [comment]
Made changes to now read current stack using get_results() API function, which appears to do the job... but can hold off until I've properly checked the outputs; I'm now more wary that there might be something else I've missed given I haven't previously used the stretching feature. 

Will update when I'm confident it is working as intended.

**Comment by asyates** [comment]
Looks fine to me! Should be good to merge.

mwcs_stretch

**Comment by ThomasLecocq** [comment]
thanks a bunch !

**Pull request merged**
