### PR TITLE
MWCS colormap

### PR DESCRIPTION
**Pull request by rantanplan77**
I removed these custom cmap adjustments to make it work again.

If one wanted power-law scaling, it should be done in a clean way like [here](http://matplotlib.org/users/colormapnorms.html#power-law).

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
@rantanplan77 the idea of the custom colormap is to make sure it is centered... the way you set it up now could make the image look a bit red or a bit blue if the mean of the image is not 0.0. You should now try to find a reasonable `vmax` and set the colorscale `vmin` & `vmax` automatically, and symmetric around 0.0.

**Comment by rantanplan77** [comment]
@ThomasLecocq good point about symmetry. For me, this 99th percentile looks nice, maybe you can test with your datasets and see if it needs adjustment.

**Comment by ThomasLecocq** [comment]
@rantanplan77 how does percentile solve the non-zero-mean ?

**Comment by rantanplan77** [comment]
@ThomasLecocq I thought the colormap should be centered at 0, even if the mean != 0. This is implemented now in line 109. Should it be centered around the mean?

**Comment by ThomasLecocq** [comment]
no, you're right, it'll work...

**Comment by rantanplan77** [comment]
We can still argue if we should take the 1st or the 99th percentile or a mix, but for reasonable data it shouldn't matter too much

**Comment by ThomasLecocq** [comment]
does this change make msnoise no longer compatible with previous pandas versions ? when was the change to `resample(...).mean()` introduced?

**Comment by rantanplan77** [comment]
Looks like 0.18.0: http://pandas.pydata.org/pandas-docs/version/0.18.0/whatsnew.html#resample-api

**Comment by ThomasLecocq** [comment]
ok so add a line in `/doc/releasenotes/msnoise-1.5.rst` to remember the changes and then it's good to go for me.

**Pull request merged**
