### PR TITLE
remove obsolete nanmean in figures

### PR DESCRIPTION
**Pull request by rantanplan77**
remove obsolete import of scipy.stats.stats.nanmean, which throws an error as nanmean is now in numpy

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
Hi Lukas, 
Thanks for this. Do you know from which version onward (numpy, scipy) this change needs to be made ?

**Comment by rantanplan77** [comment]
It doesn't work in Scipy >= 0.18.0 as far as I can tell.

Cheers

**Comment by ThomasLecocq** [comment]
Ok, the test pass but they don't cover the figures :) I'll have a look at it using my current installs , in theory, we should make it backward compatible etc...

**Comment by rantanplan77** [comment]
I think it actually is backward compatible - nanmean is imported in these figures but never called.

**Comment by ThomasLecocq** [comment]
aaaaah, that's completely possible :)

**Pull request merged**
