### PR TITLE
Insert info about DIST, AZIM,BAZIM in file heaters (If export format = SAC)

### PR DESCRIPTION
**Pull request by carmelosammarco**

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
@carmelosammarco : looks cool... but... could you create your changes on the latest MASTER release ? this is a very very out-dated version (database_tools.py tries to be re-created, it's now called "API") etc... ?

**Comment by carmelosammarco** [comment]
i did it!!! i change the master one... but in my branch.. is it correct?

**Comment by ThomasLecocq** [comment]
No, unless you have updated the master in your fork first... 

So steps are:
* fork MSNoise (if already done: sync your fork with the official "upstream" (=here): https://help.github.com/articles/syncing-a-fork/
* create a new branch from your updated master
* modify your branch
* test
* PR 

:-)

**Comment by ThomasLecocq** [comment]
@carmelosammarco : looks OK but could you:
* keep the `session` argument as ALWAYS first
* remove the comments in api.py

**Comment by carmelosammarco** [comment]
comments removed... in witch way can I keep the session argument as ALWAYS first?

**Comment by ThomasLecocq** [comment]
You don't have to close the PR for that, just update & push...

for the session stuff

do
```
def somefunction(session, sta1, sta2,...):

```
instead of

```
def somefunction(sta1, sta2, session...):

```

**Comment by ThomasLecocq** [comment]
why did you delete your branch :)

**Comment by carmelosammarco** [comment]
i did all from the beginning... i have a new brach now.. :) and a new pull request..

**Comment by carmelosammarco** [comment]
ok i understand now "keep the session argument as ALWAYS first" :)

**Comment by ThomasLecocq** [comment]
so now, don't delete this branch, just edit your files, commit + push and it will automatically update here !

**Comment by carmelosammarco** [comment]
ok!!! :)

**Pull request closed without merging**
