### PR TITLE
Improve plot titles

### PR DESCRIPTION
**Pull request by rantanplan77**
This works, I don't know if there is a better way to read out the filter used.

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
It's a good idea, and needed. While you're at it, could you also include the mov_stack value ? And the components used?

**Comment by rantanplan77** [comment]
Sure!

**Comment by rantanplan77** [comment]
I think 2 digits should be fine for most applications.

**Comment by ThomasLecocq** [comment]
test pass (obviously, plots are not tested :-) )

I'm thinking of building the documentation on a "real project", like Undervolc used in the SRL paper. So example plots would contain real data. And images could be tested.

I'll add a "contributors" file in the repo later today, please add your name to it !

Thomas

**Comment by ThomasLecocq** [comment]
@rantanplan77 = edit the Contributors.txt file to add your name :-) (who are you ? ;) )

**Pull request merged**
