### PR TITLE
fix mask for more than 2 traces

### PR DESCRIPTION
**Pull request by omrivolk**
MSNoise was crashing because I had 4 traces in a stream. This fixed the problem for any length of stream.

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
Hi, could you check that it's not corrected by the maintenance branch?

**Comment by ThomasLecocq** [comment]
could you rebase this on the maintenance branch and PR in there ? so I can merge it with the 1.6.1 maintenance this week ?

**Comment by ThomasLecocq** [comment]
Hi,

could you rebase your PR on current master ?

**Comment by omrivolk** [comment]
Yes, will do

**Pull request closed without merging**
