### PR TITLE
Info about distance in Cross_correlation(export=SAC)

### PR DESCRIPTION
**Pull request by carmelosammarco**
I did this modification on an old version of this program and they worked very well. Now the scripts look very different and also with different function. So i hope that this time my modification works!! @ThomasLecocq if this pull request doesn't pass the check with travis-c  It means that i  need more time to understand the new structure but i will find a way!! :)

### CODE REVIEW

**Comment by ThomasLecocq** [comment]
@carmelosammarco : do the test pass on your machine ? You should test locally before pushing to GitHub :)

**Comment by carmelosammarco** [comment]
@ThomasLecocq OK!! :) i realised now that every time i do a commit, travis-c test it for me.. the next modifications i  will try on my machine.. So every time i need to try on my machine i need to "python setup.py install" again with the new modify scripts.. after new folder and "msnoise test" right?? It is better uninstall msnoise before test again?

**Comment by ThomasLecocq** [comment]
in theory yes, but you could just work in your directory and run python setup.py develop and then test elsewhere. Just note you need to delete msnoise from the site-packages/ before developping.

you can "commit" locally to keep track of what you do, but only push when the tests pass !

**Comment by ThomasLecocq** [comment]
@carmelosammarco : don't worry about the failures etc... I'll try to merge your suggestions asap in master directly very soon...

**Comment by ThomasLecocq** [comment]
this is no longer relevant with the workflows of MSNoise 2, I believe. But I think we should provide more examples on how to export the newly created xarray files.

**Pull request closed without merging**
